### ISSUE TITLE
Evalution and inference

### ISSUE THREAD

**Issue by wawatsmart** [ellenmellon/DIALKI#1]
Can you update evaluation and inference section please

**Comment by Wenze7** [comment]
Hi! glad to see your great work, I want to run this project without internet, how can I train wow with dataset downloaded by myself?

**Comment by Wenze7** [comment]
> Can you update evaluation and inference section please

But when I run 'gen_wow_json.sh', it will download 'wow' from internet, can you tell me the  format of wow processed by 'gen_wow_json.sh' so that I can process dataset by myself.  Thank you!

**Comment by ellenmellon** [comment]
Hi, thank you for your interest! Sorry for the delay, but we will make sure to update the eval and inference this week. In the meantime, you can refer to the inference steps on the dev set during training included in train_reader.py for details. 

For the second question, you can first run the command of line 7 in run.sh to download the wow data and create a folder named as ./wow. After it's done, you can then move the folder to your server by running commands of line 8 & 9 in run.sh (which do not require internet access).

**Comment by ellenmellon** [comment]
What I mean is that you can download the data in a local machine with internet access by running gen_wow_json.sh, and then move the data to the actual server for training and inference.

**Comment by Wenze7** [comment]
> 

Thanks for your reply, I'm going to try it and hope it works!

**Comment by Wenze7** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/55132749/160266741-1a4455a3-3e27-4857-80a7-ea2fffc57fe5.png">
I got this result! Is it right?

**Comment by Wenze7** [comment]
> What I mean is that you can download the data in a local machine with internet access by running gen_wow_json.sh, and then move the data to the actual server for training and inference.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/55132749/160266781-e6266ae6-7853-4e43-8529-03b0934ea0e6.png">
I got this result! Is it right?

**Comment by wawatsmart** [comment]
If we want to see code for generation response, in where script we can see it?

**Comment by wawatsmart** [comment]
And can you tell me what is baseline of this experiment

**Comment by ellenmellon** [comment]
I think the files look right, but let us know if you see any issue running the following data precessing and training pipelines. To answer your question about generation, since it is not our main results, we haven't cleaned up the code for the generation part yet. But what we basically did was reusing the code from Doc2dial [here](https://github.com/doc2dial/sharedtask-dialdoc2021) with replacing the generation model (BART) input to be a concatenation of our extracted knowledge, corresponding passage and the dialogue context.

**Comment by Wenze7** [comment]
> I think the files look right, but let us know if you see any issue running the following data precessing and training pipelines. To answer your question about generation, since it is not our main results, we haven't cleaned up the code for the generation part yet. But what we basically did was reusing the code from Doc2dial [here](https://github.com/doc2dial/sharedtask-dialdoc2021) with replacing the generation model (BART) input to be a concatenation of our extracted knowledge, corresponding passage and the dialogue context.

Thanks, but when I training the model, there is an error in 'utils/options.py' line 444 .
torch.distributed.init_process_group(
            backend='nccl',
            init_method=dist_init_method,
            rank=args.local_rank,
            world_size=word_size)
The error is 'Connect() timed out', is means should I use internet?

**Comment by boru-roylu** [comment]
To figure out the issue, could you let us know your detailed environment, such as PyTorch version, GPU model, # GPU? How do you run the script?

**Comment by Wenze7** [comment]
> 
Here are details of my environment: torch1.8.0, cuda11, V100 32G. I follow this project to run the script.

**Comment by ellenmellon** [comment]
The error might come from your server network settings .. You may try searching for some similar threads [here](https://discuss.dgl.ai/t/time-out-when-lauching-distributed-training/1914/9) and [there](https://github.com/pytorch/fairseq/issues/604).

**Comment by wawatsmart** [comment]
Is the evaluation and inference has been update?

**Comment by wawatsmart** [comment]
I want to do evaluation to compare the system and produce the same thing with evaluation table in the paper. Could you upload the evaluation part please...

**Comment by ellenmellon** [comment]
Hey sorry, I think @boru-roylu has already got that done and he should be able upload very soon, plus our pretrained models.. Sorry for the delay.

**Comment by wawatsmart** [comment]
I didn't see any update. I will wait it. Thank you ellen

**Comment by ellenmellon** [comment]
Hi some update, we will make sure to get it uploaded tomorrow morning due to some commitments tonight. Again, thanks for your patience. It should be up soon.
