### ISSUE TITLE
'sequence_output' is a string not a tensor

### ISSUE THREAD

**Issue by Wenze7** [ellenmellon/DIALKI#2]
Thanks for your patience！
I'm sorry that there is a new error again... The `'sequence_output'` in the follow link is a string not a tensor.
https://github.com/ellenmellon/DIALKI/blob/fc0b36ceee55184b42877d8fc9503b69369af01c/models/hf_models.py#L115 
I really don't know why?
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/55132749/160408785-e5d5f116-af52-4cac-88bd-5683bd25d3d5.png">

**Comment by ellenmellon** [comment]
Did you use [our script](https://github.com/ellenmellon/DIALKI/blob/main/download_hf_model.py) to download the pretrained models? If not, you will need to change the config "return_dict" to be false yourself.
