### ISSUE TITLE
Get different results in Doc2dial test set.

### ISSUE THREAD

**Issue by L1ttleBad** [ellenmellon/DIALKI#5]
After adding fake dialog acts and reference spans to the original Doc2dial dataset, I get inference results from the given checkpoint.
I upload them to EvalAI and get a result of {"F1": 71.03839042449137, "Exact_Match": 59.46632782719187}. It's different from the 
result in paper which is {"F1":73.1, "Exact_Match":61.8}.
The uploaded test file is [here](https://drive.google.com/file/d/1geiwa1O_M4AwIxVjQHfsnDv6GXLyhM0M/view?usp=sharing)
I wonder if there is any question in my process of getting inference results. Or is there a different way of getting results?

Thanks.

**Comment by ellenmellon** [comment]
Hi, thanks for your interest! The checkpoint we provided should be bert-base and therefore the numbers you got are consistent with what we report in the paper.

**Comment by L1ttleBad** [comment]
Sorry for my misunderstanding. It all make sense now.
Thanks for your reply.
